apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagp-devops-assignment
  labels:
    app: nagp-devops
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nagp-devops
  template:
    metadata:
      labels:
        app: nagp-devops
    spec:
      containers:
        - name: tomcat
          image: dtr.nagarro.com:443/i-nimitjohri-master
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nagp-devops-service 
spec:
  type: NodePort
  selector:
    app: nagp-devops
  ports:
  - port: port8080
    protocol: TCP
    nodePort: {{ .Values.nodeport}}
    port: 8080
    targetPort: 8080
